title: Developer's Thought ğŸ‘¨ğŸ»â€ğŸ’»  
#description: My Personal Stack Problems
author: Sagar Jadhav
github: https://github.com/sagar-jadhav
about:  Backend Developer
#disqus_shortname: stackproblems
google_analytics: UA-140202224-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    #- icon: fa-facebook
    #  link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/SagarJadhv23"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/sagarjadhv23"
    #- icon: fa-stack-exchange
    #  link: "#"
    - icon: fa-github
      link: "https://github.com/sagar-jadhav"

share:
  twitter_username: SagarJadhv23
  #fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    #- text: My Projects
    #  url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://developersthought.in/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
