title: Developer's Thought
#description: My Personal Stack Problems
author: Sagar Jadhav
github: https://github.com/sagar-jadhav
about:  â˜ï¸  Cloud Developer, IBM Software Labs | ğŸ”¥YouTuber | ğŸ‘¨ğŸ»â€ğŸ’» Speaker | ğŸ³Technology Enthusiast
#disqus_shortname: stackproblems
#google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "SagarJadhv23"
    - icon: fa-linkedin
      link: "SagarJadhv23"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/sagar-jadhav"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    #- text: My Projects
    #  url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "http://sagar-jadhav.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
